CREATE TABLE Asignaturas
(
Codigo INT NOT NULL,
NomAs VARCHAR(100) NOT NULL,
Curso INT NOT NULL,
PRIMARY KEY (Codigo)
);

CREATE TABLE Provincia
(
CodPro INT NOT NULL,
NomPr VARCHAR(50) NOT NULL,
PRIMARY KEY (CodPro)
);

CREATE TABLE Localidad
(
CodLoc INT NOT NULL,
NomLc VARCHAR(50) NOT NULL,
CodPro INT NOT NULL,
PRIMARY KEY (CodLoc),
FOREIGN KEY (CodPro) REFERENCES Provincia(CodPro)
);

CREATE TABLE Direccion
(
Planta INT,
Bloque INT,
Numero INT NOT NULL,
Puerta INT,
Ala INT,
Calle VARCHAR(100) NOT NULL,
CP CHAR(5) NOT NULL,
CodDir INT NOT NULL,
CodLoc INT NOT NULL,
PRIMARY KEY (CodDir),
FOREIGN KEY (CodLoc) REFERENCES Localidad(CodLoc)
);

CREATE TABLE Alumno
(
Codal INT NOT NULL,
NomAl VARCHAR(50) NOT NULL,
Apellido1 VARCHAR(50) NOT NULL,
Apellido2 VARCHAR(50),
DNI CHAR(9) UNIQUE,
CodDir INT NOT NULL,
PRIMARY KEY (Codal),
FOREIGN KEY (CodDir) REFERENCES Direccion(CodDir)
);

CREATE TABLE Asiste
(
Codal INT NOT NULL,
Codigo INT NOT NULL,
PRIMARY KEY (Codal, Codigo),
FOREIGN KEY (Codal) REFERENCES Alumno(Codal),
FOREIGN KEY (Codigo) REFERENCES Asignaturas(Codigo)
);
